name: tint
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python==3.9.7
  - cudatoolkit==11.6
  - pytorch-cuda=11.6
  - captum=0.7.0
  - numpy=1.24.3
  - optuna=3.5.0
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - pytorch-lightning=2.1.3
  - torchmetrics=1.2.1