#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=HMM_Weights_Classifier
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=hmm_weights_classifier_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate factai
cd $HOME/factai/

rm -f results.csv
python ./experiments/hmm/reset.py -e main
python ./experiments/hmm/main.py --explainers none --device cuda --fold 1