#!/bin/bash

#SBATCH --partition=rome
#SBATCH --gres=cpu:18
#SBATCH --cpus-per-task=18
#SBATCH --job-name=HMM_Experiment
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=hmm_weights_classifier_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate factai
cd $HOME/factai/

rm -f results.csv
python ./experiments/hmm/reset.py -e main
python ./experiments/hmm/main.py --explainers extremal_mask --device cuda --fold 1