#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=HMM_Experiment
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=lime_experiment_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate factai
cd $HOME/factai/


rm -f results.csv
python ./experiments/hmm/reset.py -e main
echo "starting assesment"
python ./experiments/hmm/main.py --device cuda --explainers deep_lift
echo "finished assessment"
current_time=$(date "+%Y.%m.%d-%H.%M.%S")
cp results.csv ./experiments/hmm/reproducibility_results/${current_time}_results.csv
