#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=HMM_Experiment
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=preservation_%A.out

module purge
module load 2022
module load Anaconda3/2022.05
source activate factai
cd $HOME/factai/experiments/hmm
rm -f preservation.csv
python reset.py -e preservation


python main.py --preservation_mode true --preservation_test true --explainers extremal_mask --device cpu --fold 0 --seed 42 --lambda-1 1 --lambda-2 1 --output-file preservation.csv --deterministic --retrain_classifier false

python main.py --preservation_mode false --preservation_test true --explainers extremal_mask --device cpu --fold 0 --seed 42 --lambda-1 1 --lambda-2 1 --output-file preservation.csv --deterministic --retrain_classifier false

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
cp preservation.csv ./experiments/hmm/results/preservation_${current_time}.csv
